export const AGENT_ORCHESTRATOR = Symbol('AGENT_ORCHESTRATOR');
export const PLANNING_AGENT_RUN_STORE = Symbol('PLANNING_AGENT_RUN_STORE');
export const PLANNING_GATEWAY = Symbol('PLANNING_GATEWAY');
export const PLANNING_MODEL_FETCH = Symbol('PLANNING_MODEL_FETCH');
