import type { Kysely } from 'kysely';
import type { Database } from '../types.js';
export interface ActionRequestRecord { id: string; tripId: string; resourceId: string; kind: string; risk: string; requestedAmount?: unknown; supplierId?: string; bookingType?: string; refundable?: boolean; offerSnapshotHash?: string; requestedSensitiveFields?: string[]; status: string; reasons: unknown[]; expiresAt: string; version: number; ownerId: string; decisionActorId?: string; decisionReason?: string; policySnapshot?: unknown; requestHash: string; requestId?: string; correlationId: string; consumedAt?: string }
const toRecord = (row: any): ActionRequestRecord => { const payload = JSON.parse(row.payload_json); return { ...payload, id: row.id, status: row.status, version: row.version, ownerId: row.owner_id, requestHash: row.request_hash, policySnapshot: row.policy_snapshot_json ? JSON.parse(row.policy_snapshot_json) : undefined, decisionActorId: row.decision_actor_id ?? undefined, decisionReason: row.decision_reason ?? undefined, requestId: row.request_id ?? payload.requestId ?? undefined, correlationId: row.correlation_id, expiresAt: row.expires_at, consumedAt: row.consumed_at ?? undefined }; };
export class ActionRequestRepository {
  constructor(private readonly db: Kysely<Database>) {}
  async create(record: ActionRequestRecord): Promise<void> { await this.db.insertInto('action_requests').values({ id: record.id, trip_id: record.tripId, owner_id: record.ownerId, version: record.version, status: record.status, payload_json: JSON.stringify(record), request_hash: record.requestHash, policy_snapshot_json: record.policySnapshot ? JSON.stringify(record.policySnapshot) : null, decision_actor_id: record.decisionActorId ?? null, decision_reason: record.decisionReason ?? null, request_id: record.requestId ?? null, correlation_id: record.correlationId, expires_at: record.expiresAt, consumed_at: record.consumedAt ?? null, created_at: new Date().toISOString() }).execute(); }
  async get(id: string): Promise<ActionRequestRecord | null> { const row = await this.db.selectFrom('action_requests').selectAll().where('id', '=', id).executeTakeFirst(); return row ? toRecord(row) : null; }
  async save(record: ActionRequestRecord): Promise<void> { const result = await this.db.updateTable('action_requests').set({ version: record.version, status: record.status, payload_json: JSON.stringify(record), policy_snapshot_json: record.policySnapshot ? JSON.stringify(record.policySnapshot) : null, decision_actor_id: record.decisionActorId ?? null, decision_reason: record.decisionReason ?? null, consumed_at: record.consumedAt ?? null }).where('id', '=', record.id).where('version', '=', record.version - 1).executeTakeFirst(); if (Number(result.numUpdatedRows ?? 0) !== 1) throw new Error('action request version conflict'); }
}
