import { createHash } from 'node:crypto';
import type { Kysely } from 'kysely';
import type { TravelMandate } from '@travel/contracts';
import type { Database, MandatesTable } from '../types.js';
export interface VersionedMandate extends TravelMandate { ownerId: string; actorId: string; createdAt: string; policyHash: string }
const hash = (mandate: TravelMandate) => createHash('sha256').update(JSON.stringify(mandate)).digest('hex');
const toMandate = (row: MandatesTable): VersionedMandate => ({ ...JSON.parse(row.payload_json) as TravelMandate, id: row.id, version: row.version, tripId: row.trip_id, ownerId: row.owner_id, actorId: row.actor_id, createdAt: row.created_at, policyHash: row.policy_hash, validUntil: row.valid_until, revokedAt: row.revoked_at ?? undefined });
export class MandateRepository {
  constructor(private readonly db: Kysely<Database>) {}
  async create(ownerId: string, input: Omit<TravelMandate, 'version' | 'revokedAt'>, actorId = ownerId, now = new Date().toISOString()): Promise<VersionedMandate> { const mandate = { ...structuredClone(input), version: 1 } as TravelMandate; await this.db.insertInto('mandates').values({ id: mandate.id, version: 1, trip_id: mandate.tripId, owner_id: ownerId, payload_json: JSON.stringify(mandate), policy_hash: hash(mandate), actor_id: actorId, created_at: now, valid_until: mandate.validUntil, revoked_at: null }).execute(); return { ...mandate, ownerId, actorId, createdAt: now, policyHash: hash(mandate) }; }
  async get(id: string, ownerId?: string, version?: number): Promise<VersionedMandate | null> { let query = this.db.selectFrom('mandates').selectAll().where('id', '=', id); if (ownerId) query = query.where('owner_id', '=', ownerId); query = version === undefined ? query.orderBy('version', 'desc') : query.where('version', '=', version); const row = await query.executeTakeFirst(); return row ? toMandate(row) : null; }
  async listByTrip(tripId: string, ownerId: string): Promise<VersionedMandate[]> { const rows = await this.db.selectFrom('mandates').selectAll().where('trip_id', '=', tripId).where('owner_id', '=', ownerId).orderBy('version', 'desc').execute(); return rows.map(toMandate); }
  async amend(id: string, ownerId: string, expectedVersion: number, patch: Partial<Omit<TravelMandate, 'id' | 'tripId' | 'version' | 'revokedAt'>>, actorId = ownerId, now = new Date().toISOString()): Promise<VersionedMandate> { const current = await this.get(id, ownerId); if (!current) throw new Error('mandate not found'); if (current.version !== expectedVersion) throw new Error('mandate version changed'); const next = { ...current, ...structuredClone(patch), version: current.version + 1, revokedAt: undefined } as TravelMandate; await this.db.insertInto('mandates').values({ id, version: next.version, trip_id: next.tripId, owner_id: ownerId, payload_json: JSON.stringify(next), policy_hash: hash(next), actor_id: actorId, created_at: now, valid_until: next.validUntil, revoked_at: null }).execute(); return { ...next, ownerId, actorId, createdAt: now, policyHash: hash(next) }; }
  async revoke(id: string, ownerId: string, expectedVersion: number, actorId = ownerId, now = new Date().toISOString()): Promise<VersionedMandate> { const current = await this.get(id, ownerId); if (!current) throw new Error('mandate not found'); if (current.version !== expectedVersion) throw new Error('mandate version changed'); const next = { ...current, version: current.version + 1, revokedAt: now } as TravelMandate; await this.db.insertInto('mandates').values({ id, version: next.version, trip_id: next.tripId, owner_id: ownerId, payload_json: JSON.stringify(next), policy_hash: hash(next), actor_id: actorId, created_at: now, valid_until: next.validUntil, revoked_at: now }).execute(); return { ...next, ownerId, actorId, createdAt: now, policyHash: hash(next) }; }
}
